[build]
builder = "nixpacks"
buildCommand = "cd worker && npm install && npm run build"

[deploy]
startCommand = "cd worker && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
